### ISSUE TITLE
Song plays from cache are not being shown on Subsonic server

### ISSUE THREAD

**Issue by elduderino5k** [einsteinx2/libSub#3]
Subsonic 5.2.1 and latest iSub client - iSub song plays from cache are not displayed or recorded on Subsonic server.  This was working in previous versions of Subsonic such as 4.7, with the current latest most recent version of iSub.

**Comment by einsteinx2** [comment]
Unfortunately Sunsonic doesn't have a way to report song plays for cached songs or offline play (still years later after I requested it). So I was using a hack of streaming the song then immediately canceling the stream. But subsonic no longer counts those as plays. Not much I can do without Subsonic support here.
